DB:
  AutoCreateTable: true
  Driver: "postgresql"
  DriverName: "tierup"
  Host: "118.178.180.247"
  Port: "5432"
  User: "tierup"
  Password: "DnMMirY6jy2FsQf6"
  Charset: "utf8mb4"
WebApi:
  Host: "127.0.0.1"
  Port: "88"
