// Code generated by gen_crud_swagger.go; DO NOT EDIT.
package crud

import (
	"github.com/gin-gonic/gin"
)


// CreateMenu godoc
// @Summary 创建Menu
// @Tags Menu
// @Accept json
// @Produce json
// @Param data body model.Menu true "Menu信息"
// @Success 200 {object} model.Menu
// @Router /api/v1/menu/create [post]
func CreateMenu(c *gin.Context) {
	 
}

// UpdateMenu godoc
// @Summary 更新Menu
// @Tags Menu
// @Accept json
// @Produce json
// @Param id path int true "ID"
// @Param data body model.Menu true "Menu信息"
// @Success 200 {object} model.Menu
// @Router /api/v1/menu/update/{id} [put]
func UpdateMenu(c *gin.Context) {
	 
}

// DeleteMenu godoc
// @Summary 删除Menu
// @Tags Menu
// @Param id path int true "ID"
// @Success 200 {object} map[string]interface{}
// @Router /api/v1/menu/delete/{id} [delete]
func DeleteMenu(c *gin.Context) {
	 
}

// PageMenu godoc
// @Summary 分页查询Menu
// @Tags Menu
// @Param page query int false "页码"
// @Param pageSize query int false "每页数量"
// @Success 200 {object} []model.Menu
// @Router /api/v1/menu/page [get]
func PageMenu(c *gin.Context) {
 
}

// CreateRole godoc
// @Summary 创建Role
// @Tags Role
// @Accept json
// @Produce json
// @Param data body model.Role true "Role信息"
// @Success 200 {object} model.Role
// @Router /api/v1/role/create [post]
func CreateRole(c *gin.Context) {
	 
}

// UpdateRole godoc
// @Summary 更新Role
// @Tags Role
// @Accept json
// @Produce json
// @Param id path int true "ID"
// @Param data body model.Role true "Role信息"
// @Success 200 {object} model.Role
// @Router /api/v1/role/update/{id} [put]
func UpdateRole(c *gin.Context) {
	 
}

// DeleteRole godoc
// @Summary 删除Role
// @Tags Role
// @Param id path int true "ID"
// @Success 200 {object} map[string]interface{}
// @Router /api/v1/role/delete/{id} [delete]
func DeleteRole(c *gin.Context) {
	 
}

// PageRole godoc
// @Summary 分页查询Role
// @Tags Role
// @Param page query int false "页码"
// @Param pageSize query int false "每页数量"
// @Success 200 {object} []model.Role
// @Router /api/v1/role/page [get]
func PageRole(c *gin.Context) {
 
}

// CreateUser godoc
// @Summary 创建User
// @Tags User
// @Accept json
// @Produce json
// @Param data body model.User true "User信息"
// @Success 200 {object} model.User
// @Router /api/v1/user/create [post]
func CreateUser(c *gin.Context) {
	 
}

// UpdateUser godoc
// @Summary 更新User
// @Tags User
// @Accept json
// @Produce json
// @Param id path int true "ID"
// @Param data body model.User true "User信息"
// @Success 200 {object} model.User
// @Router /api/v1/user/update/{id} [put]
func UpdateUser(c *gin.Context) {
	 
}

// DeleteUser godoc
// @Summary 删除User
// @Tags User
// @Param id path int true "ID"
// @Success 200 {object} map[string]interface{}
// @Router /api/v1/user/delete/{id} [delete]
func DeleteUser(c *gin.Context) {
	 
}

// PageUser godoc
// @Summary 分页查询User
// @Tags User
// @Param page query int false "页码"
// @Param pageSize query int false "每页数量"
// @Success 200 {object} []model.User
// @Router /api/v1/user/page [get]
func PageUser(c *gin.Context) {
 
}

// CreateUserRole godoc
// @Summary 创建UserRole
// @Tags UserRole
// @Accept json
// @Produce json
// @Param data body model.UserRole true "UserRole信息"
// @Success 200 {object} model.UserRole
// @Router /api/v1/userrole/create [post]
func CreateUserRole(c *gin.Context) {
	 
}

// UpdateUserRole godoc
// @Summary 更新UserRole
// @Tags UserRole
// @Accept json
// @Produce json
// @Param id path int true "ID"
// @Param data body model.UserRole true "UserRole信息"
// @Success 200 {object} model.UserRole
// @Router /api/v1/userrole/update/{id} [put]
func UpdateUserRole(c *gin.Context) {
	 
}

// DeleteUserRole godoc
// @Summary 删除UserRole
// @Tags UserRole
// @Param id path int true "ID"
// @Success 200 {object} map[string]interface{}
// @Router /api/v1/userrole/delete/{id} [delete]
func DeleteUserRole(c *gin.Context) {
	 
}

// PageUserRole godoc
// @Summary 分页查询UserRole
// @Tags UserRole
// @Param page query int false "页码"
// @Param pageSize query int false "每页数量"
// @Success 200 {object} []model.UserRole
// @Router /api/v1/userrole/page [get]
func PageUserRole(c *gin.Context) {
 
}
