basePath: /api/v1
definitions:
  controller.PasswordRequest:
    properties:
      new_password:
        maxLength: 100
        minLength: 6
        type: string
      old_password:
        type: string
    required:
    - new_password
    - old_password
    type: object
  controller.RoleRequest:
    properties:
      role_id:
        type: integer
    required:
    - role_id
    type: object
  model.Menu:
    properties:
      code:
        type: integer
      component:
        type: string
      created_at:
        type: string
      icon:
        type: string
      id:
        type: integer
      name:
        type: string
      note:
        type: string
      parentId:
        type: integer
      path:
        type: string
      sort:
        type: integer
      status:
        type: integer
      type:
        type: integer
      updated_at:
        type: string
    type: object
  model.Role:
    properties:
      created_at:
        type: string
      description:
        type: string
      display_name:
        type: string
      id:
        type: integer
      name:
        type: string
      updated_at:
        type: string
      users:
        items:
          $ref: '#/definitions/model.User'
        type: array
    type: object
  model.User:
    properties:
      avatar:
        type: string
      created_at:
        type: string
      email:
        type: string
      id:
        type: integer
      nickname:
        type: string
      phone:
        type: string
      roles:
        items:
          $ref: '#/definitions/model.Role'
        type: array
      status:
        description: 1:正常, 0:禁用
        type: integer
      updated_at:
        type: string
      username:
        type: string
    type: object
  model.UserRole:
    properties:
      roleID:
        type: integer
      userID:
        type: integer
    type: object
  service.LoginRequest:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  service.PermissionRequest:
    properties:
      method:
        type: string
      path:
        type: string
      role:
        type: string
    required:
    - method
    - path
    - role
    type: object
  service.RegisterRequest:
    properties:
      email:
        type: string
      nickname:
        type: string
      password:
        maxLength: 100
        minLength: 6
        type: string
      phone:
        type: string
      username:
        maxLength: 50
        minLength: 3
        type: string
    required:
    - email
    - password
    - username
    type: object
host: localhost:88
info:
  contact: {}
  description: Tier Up项目的API服务
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Tier Up API
  version: "1.0"
paths:
  /api/v1/menu/create:
    post:
      consumes:
      - application/json
      parameters:
      - description: Menu信息
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/model.Menu'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Menu'
      summary: 创建Menu
      tags:
      - Menu
  /api/v1/menu/delete/{id}:
    delete:
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: 删除Menu
      tags:
      - Menu
  /api/v1/menu/page:
    get:
      parameters:
      - description: 页码
        in: query
        name: page
        type: integer
      - description: 每页数量
        in: query
        name: pageSize
        type: integer
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Menu'
            type: array
      summary: 分页查询Menu
      tags:
      - Menu
  /api/v1/menu/update/{id}:
    put:
      consumes:
      - application/json
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: integer
      - description: Menu信息
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/model.Menu'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Menu'
      summary: 更新Menu
      tags:
      - Menu
  /api/v1/role/create:
    post:
      consumes:
      - application/json
      parameters:
      - description: Role信息
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/model.Role'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Role'
      summary: 创建Role
      tags:
      - Role
  /api/v1/role/delete/{id}:
    delete:
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: 删除Role
      tags:
      - Role
  /api/v1/role/page:
    get:
      parameters:
      - description: 页码
        in: query
        name: page
        type: integer
      - description: 每页数量
        in: query
        name: pageSize
        type: integer
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Role'
            type: array
      summary: 分页查询Role
      tags:
      - Role
  /api/v1/role/update/{id}:
    put:
      consumes:
      - application/json
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: integer
      - description: Role信息
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/model.Role'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Role'
      summary: 更新Role
      tags:
      - Role
  /api/v1/user/create:
    post:
      consumes:
      - application/json
      parameters:
      - description: User信息
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/model.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.User'
      summary: 创建User
      tags:
      - User
  /api/v1/user/delete/{id}:
    delete:
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: 删除User
      tags:
      - User
  /api/v1/user/page:
    get:
      parameters:
      - description: 页码
        in: query
        name: page
        type: integer
      - description: 每页数量
        in: query
        name: pageSize
        type: integer
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.User'
            type: array
      summary: 分页查询User
      tags:
      - User
  /api/v1/user/update/{id}:
    put:
      consumes:
      - application/json
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: integer
      - description: User信息
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/model.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.User'
      summary: 更新User
      tags:
      - User
  /api/v1/userrole/create:
    post:
      consumes:
      - application/json
      parameters:
      - description: UserRole信息
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/model.UserRole'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.UserRole'
      summary: 创建UserRole
      tags:
      - UserRole
  /api/v1/userrole/delete/{id}:
    delete:
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: 删除UserRole
      tags:
      - UserRole
  /api/v1/userrole/page:
    get:
      parameters:
      - description: 页码
        in: query
        name: page
        type: integer
      - description: 每页数量
        in: query
        name: pageSize
        type: integer
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.UserRole'
            type: array
      summary: 分页查询UserRole
      tags:
      - UserRole
  /api/v1/userrole/update/{id}:
    put:
      consumes:
      - application/json
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: integer
      - description: UserRole信息
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/model.UserRole'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.UserRole'
      summary: 更新UserRole
      tags:
      - UserRole
  /login:
    post:
      consumes:
      - application/json
      description: 用户登录获取令牌
      parameters:
      - description: 用户登录信息
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/service.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 登录成功，返回token
          schema:
            additionalProperties: true
            type: object
        "400":
          description: 参数错误
          schema:
            additionalProperties: true
            type: object
        "401":
          description: 登录失败
          schema:
            additionalProperties: true
            type: object
      summary: 用户登录
      tags:
      - User
  /permission:
    delete:
      consumes:
      - application/json
      description: 移除角色的访问路径权限
      parameters:
      - description: 权限信息
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/service.PermissionRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 移除成功
          schema:
            additionalProperties: true
            type: object
        "400":
          description: 参数错误
          schema:
            additionalProperties: true
            type: object
        "500":
          description: 移除权限失败
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: 移除权限
      tags:
      - 权限管理
    post:
      consumes:
      - application/json
      description: 为角色添加访问路径的权限
      parameters:
      - description: 权限信息
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/service.PermissionRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 添加成功
          schema:
            additionalProperties: true
            type: object
        "400":
          description: 参数错误
          schema:
            additionalProperties: true
            type: object
        "500":
          description: 添加权限失败
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: 添加权限
      tags:
      - 权限管理
  /register:
    post:
      consumes:
      - application/json
      description: 注册新用户
      parameters:
      - description: 用户注册信息
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/service.RegisterRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 注册成功
          schema:
            additionalProperties: true
            type: object
        "400":
          description: 参数错误
          schema:
            additionalProperties: true
            type: object
        "500":
          description: 注册失败
          schema:
            additionalProperties: true
            type: object
      summary: 用户注册
      tags:
      - User
  /role-permissions/{name}:
    get:
      consumes:
      - application/json
      description: 获取指定角色的所有权限
      parameters:
      - description: 角色名称
        in: path
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 权限列表
          schema:
            additionalProperties: true
            type: object
        "400":
          description: 角色名称不能为空
          schema:
            additionalProperties: true
            type: object
        "500":
          description: 获取角色权限失败
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: 获取角色权限
      tags:
      - 权限管理
  /role/{id}:
    get:
      consumes:
      - application/json
      description: 根据ID获取角色详情
      parameters:
      - description: 角色ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 角色详情
          schema:
            additionalProperties: true
            type: object
        "400":
          description: 无效的角色ID
          schema:
            additionalProperties: true
            type: object
        "500":
          description: 获取角色失败
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: 获取角色详情
      tags:
      - Role
  /user/{id}/role:
    delete:
      consumes:
      - application/json
      description: 从指定用户移除角色
      parameters:
      - description: 用户ID
        in: path
        name: id
        required: true
        type: integer
      - description: 角色信息
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/controller.RoleRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 移除成功
          schema:
            additionalProperties: true
            type: object
        "400":
          description: 参数错误
          schema:
            additionalProperties: true
            type: object
        "500":
          description: 移除角色失败
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: 移除用户的角色
      tags:
      - User
    post:
      consumes:
      - application/json
      description: 为指定用户分配角色
      parameters:
      - description: 用户ID
        in: path
        name: id
        required: true
        type: integer
      - description: 角色信息
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/controller.RoleRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 分配成功
          schema:
            additionalProperties: true
            type: object
        "400":
          description: 参数错误
          schema:
            additionalProperties: true
            type: object
        "500":
          description: 分配角色失败
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: 分配角色给用户
      tags:
      - User
  /user/info:
    get:
      consumes:
      - application/json
      description: 获取已登录用户的详细信息
      produces:
      - application/json
      responses:
        "200":
          description: 用户信息
          schema:
            additionalProperties: true
            type: object
        "401":
          description: 未认证
          schema:
            additionalProperties: true
            type: object
        "500":
          description: 获取用户信息失败
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: 获取当前用户信息
      tags:
      - User
    put:
      consumes:
      - application/json
      description: 更新已登录用户的信息
      parameters:
      - description: 用户信息
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/model.User'
      produces:
      - application/json
      responses:
        "200":
          description: 更新成功
          schema:
            additionalProperties: true
            type: object
        "400":
          description: 参数错误
          schema:
            additionalProperties: true
            type: object
        "401":
          description: 未认证
          schema:
            additionalProperties: true
            type: object
        "500":
          description: 更新用户信息失败
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: 更新当前用户信息
      tags:
      - User
  /user/password:
    put:
      consumes:
      - application/json
      description: 修改当前用户的密码
      parameters:
      - description: 密码信息
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/controller.PasswordRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 修改成功
          schema:
            additionalProperties: true
            type: object
        "400":
          description: 参数错误
          schema:
            additionalProperties: true
            type: object
        "401":
          description: 未认证
          schema:
            additionalProperties: true
            type: object
        "500":
          description: 修改密码失败
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: 修改密码
      tags:
      - User
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
